### ISSUE TITLE
`ClighterDisable` does not work if not source files have been opened yet

### ISSUE THREAD

**Issue by petersohn** [bbchung/clighter#34]
If I have `g:clighter_autostart` set to 1, and type `:ClighterDisable` before opening a source file, clighter is still enabled upon opening a source file.

An example scenario where this can occur: clighter works normally for most source files, but for one file it crashes, causing vim to crash too. So I reopen vim, then open the file I was going to work. However, if I do this with clighter enabled, vim crashes again. So I have to disable it, but `ClighterDisable` does not help, neiher does setting `g:clighter_autostart` to 0 here (I'd have to set it in `.vimrc`, but obviously I don't want to do that).

I looked into the code and found the source of the problem. In `plugin/clighter.vim`, if `g:clighter_autostart` is set, an autocmd is set up that enables clighter when a source file is opened.

    if g:clighter_autostart
        augroup ClighterAutoStart
            au FileType c,cpp,objc,objcpp call clighter#Enable()
        augroup END
    endif

Then when the first time `clighter#Enable()` is called, that autocmd is removed.

    silent! au! ClighterAutoStart

The problem with this is that `clighter#Disable()` has no effect before `clighter#Enable()` is called at least once.

**Comment by bbchung** [comment]
has solved this problem by change FileType to VimEnter in ClighterAutoStart

**Comment by petersohn** [comment]
Your solution has broken something. I get the following error message when trying to start vim:

    Error detected while processing function clighter#Enable:
    line   22:
    Traceback (most recent call last):
    Press ENTER or type command to continue
    Error detected while processing function clighter#Enable:
    line   22:
      File "<string>", line 1, in <module>
    Press ENTER or type command to continue
    Error detected while processing function clighter#Enable:
    line   22:
    NameError: name 'vim' is not defined
    Press ENTER or type command to continue

After this, clighter works for any new files I open, but if I open vim with a source file (with `vim somefile.cpp`), then it doesn't work until I navigate away and back (doing a `:e` helps too). Completely strange things happen in the following situation:

- Open vim with a file: `vim somefile.cpp`
- Open another file in a new window: `:new otherfile.cpp`
- Navigate back to the previous window: `CTRL+P`

Now I get an error message every time I move the cursor until I fix it (again, `:e` helps).

    Error detected while processing CursorMoved Auto commands for "*":
    Traceback (most recent call last):
    Press ENTER or type command to continue
    Error detected while processing CursorMoved Auto commands for "*":
      File "<string>", line 1, in <module>
    Press ENTER or type command to continue
    Error detected while processing CursorMoved Auto commands for "*":
      File "/home/peet/.vim/bundle/clighter/autoload/../misc/highlighting.py", line 97, in hl_window
    Press ENTER or type command to continue
    Error detected while processing CursorMoved Auto commands for "*":
        if vim.current.window.vars['clighter_hl'][0] < parse_tick:
    Press ENTER or type command to continue
    Error detected while processing CursorMoved Auto commands for "*":
    KeyError: 'clighter_hl'
    Press ENTER or type command to continue

**Comment by bbchung** [comment]
fixed

**Comment by petersohn** [comment]
I checked it, but it's still not fixed. The last part about the error messages upon each cursor move has disappeared, but the other problems, such as the error message on startup is still there.

**Comment by bbchung** [comment]
can you tell me how to reproduce the bug step by step? the bug doesn't happen in my vim

**Comment by petersohn** [comment]
Your latest commit seems to have fixed it.
